baseURL = 'https://rufevean.github.io/the-rust-chronicles/'
languageCode = 'en-us'
title = 'The Rust Chronicles'
theme = 'PaperMod'

[params]
ShowShareButtons = true
ShowReadingTime = true
ShowBreadCrumbs = true
ShowCodeCopyButtons= true
author = ["rufevean"]
comments = true
Sharebuttons=['linkedin','twitter','reddit','whatsapp']

[[menu.main]]
identifier = "github"
name = "sponser"
url = "https://github.com/rufevean"
weight = 30


