baseURL = 'https://rufevean.github.io/the-rust-chronicles/'
languageCode = 'en-us'
title = 'The Rust Chronicles'
theme = 'PaperMod'

[params]
ShowShareButtons = true
ShowReadingTime = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
author = ["rufevean"]
comments = true
Sharebuttons = ['linkedin', 'twitter', 'reddit', 'whatsapp']

[[menu.main]]
identifier = "github"
name = "sponsor"
url = "https://github.com/rufevean"
weight = 30

[[menu.main]]
identifier = "github-star"
name = "give me a star \U0001F31F"
url = "https://github.com/rufevean/the-rust-chronicles"
weight = 30
